// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_submit from "./routes/api/submit.ts";
import * as $index from "./routes/index.tsx";
import * as $manage from "./routes/manage.tsx";
import * as $winner from "./routes/winner.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/submit.ts": $api_submit,
    "./routes/index.tsx": $index,
    "./routes/manage.tsx": $manage,
    "./routes/winner.tsx": $winner,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
